apiVersion: v1
data:
    password: ENC[AES256_GCM,data:1BGVT2KHh7fELg5ebeMcCA==,iv:0OuVzMYQptLWBbRrebbKOVsHVZDbUuMwUgCAH9QThXg=,tag:JKgRCcYLIcb2+mjZo8ZwDA==,type:str]
    user: ENC[AES256_GCM,data:bhXW0CWLWLo=,iv:zTNZvjGUR3vM3+55wYCe5bsMfMydd5s801sAcsy8I0w=,tag:9VBsXqDi7rtzig9BVtpg1A==,type:str]
kind: Secret
metadata:
    name: linkding-secret
sops:
    age:
        - recipient: age1hzsl78npj9jrwetc00glwppyp5pcdp82mxd4xwa0x6k7jq8g3uwq8yzsg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUXJ5ekJ3YmRRUEVXM2lE
            Nkp1RE1XVU9iT0FRR2o1bzdNWFNLaUZLTmtZClZEWFBPU0ZjTWJBQjltdC9wbEZH
            OEVJSGE0TTdkMEJNYVZ4aTYwS25FaWMKLS0tIG0xNUxUbWpZMGY1NlR3TG0xbU11
            MWNqU0oyMTdPcTh6N1p6MVZzWlFndDQK0W73EBDXkJbi/qKtQNMDxJNe084XgVnz
            9nW3rfARJCOR6v+/GgEd2qToHWTDQW96k0vhvPD3GAdm6xgZRsy+Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T03:00:50Z"
    mac: ENC[AES256_GCM,data:zJ6VI5p9yXNqUWCZhaRIYZLvrCWYRTckSp/z0Xu0N7D3wim3jRC+w7E82WG1HoTdd322aEeS86kCVWCFgOS+dnHtaFbb8mRXzgORwPKJrgte/uDzvBfGYh6BC+0vq10+XHe8Iiit43sY6dISdSdI/noBKVOhfDqG6t/A6DjKzjM=,iv:mFeFyFVUPjiIWKlu5Q217VHUqpNWYEj8w5Qop1swjLQ=,tag:b3SmvUtV0klv+fsO1x3SjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
